# Configurations for Air
[build]
# Command to start the Go application
cmd = "go build -o ./tmp/main ./cmd/main.go"  # Update this line to point to /cmd/main.go

# Location where the binary will be stored
bin = "./tmp/main"  # This is where the compiled binary will be

# Log level (optional, can be info, error, etc.)
log = "debug"

# Patterns to watch for changes (e.g., for hot reloading)
include_ext = ["go", "tpl", "html"]
exclude_dir = ["assets", "tmp"]

# If you have some specific folders or files to ignore
exclude_file = []

# Ignore any hidden files
exclude_glob = ["*.git/*"]

# Interval for file polling (optional, in seconds)
delve = "0"

# Customize the command used to run the binary
run_cmd = "./tmp/main"

[log]
level = "debug"
